nelmio_cors:
    defaults:
        allow_origin: ['https:127.0.0.1'] # Replace '*' with specific domains if needed
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/': # Adjust this to your API routes
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
