nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        forced_allow_origin_value: null
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
