<?php

namespace ContainerCe1geJO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XkU66BYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xkU66BY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xkU66BY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conversation' => ['privates', '.errored..service_locator.xkU66BY.App\\Entity\\Conversation', NULL, 'Cannot autowire service ".service_locator.xkU66BY": it needs an instance of "App\\Entity\\Conversation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'conversation' => 'App\\Entity\\Conversation',
        ]);
    }
}
