<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container87e8apL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container87e8apL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container87e8apL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container87e8apL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container87e8apL\App_KernelDevDebugContainer([
    'container.build_hash' => '87e8apL',
    'container.build_id' => 'e034237d',
    'container.build_time' => 1739191553,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container87e8apL');
