<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHNBF7DS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHNBF7DS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHNBF7DS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHNBF7DS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHNBF7DS\App_KernelDevDebugContainer([
    'container.build_hash' => 'HNBF7DS',
    'container.build_id' => '32e217d7',
    'container.build_time' => 1738678237,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHNBF7DS');
