<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKBhmYsc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKBhmYsc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKBhmYsc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKBhmYsc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKBhmYsc\App_KernelDevDebugContainer([
    'container.build_hash' => 'KBhmYsc',
    'container.build_id' => 'da8abf95',
    'container.build_time' => 1738939118,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKBhmYsc');
