<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLT8nQex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLT8nQex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLT8nQex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLT8nQex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLT8nQex\App_KernelDevDebugContainer([
    'container.build_hash' => 'LT8nQex',
    'container.build_id' => '74d36a05',
    'container.build_time' => 1738590825,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLT8nQex');
