<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNaTFz1P\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNaTFz1P/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNaTFz1P.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNaTFz1P\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNaTFz1P\App_KernelDevDebugContainer([
    'container.build_hash' => 'NaTFz1P',
    'container.build_id' => '077bc75b',
    'container.build_time' => 1738592811,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNaTFz1P');
